aws:
  access-key: ${AWS_ACCESS_KEY:testKey}
  secret-key: ${AWS_SECRET_KEY:secretKey}
  s3:
    bucket: ${AWS_S3_BUCKET:bucket}
    base-url: ${AWS_S3_BASEURL:baseUrl}



---
spring:
  config:
    activate:
      on-profile: local

  redis:
    host: localhost
    port: 6379
    password: qlalfqjsgh

---
spring:
  config:
    activate:
      on-profile: dev

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:qlalfqjsgh}

---
spring:
  config:
    activate:
      on-profile: prod

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:qlalfqjsgh}