
---
spring:
  config:
    activate:
      on-profile: local

  redis:
    host: localhost
    port: 6379
    password: qlalfqjsgh

---
spring:
  config:
    activate:
      on-profile: dev

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:qlalfqjsgh}