version: '3.7'

services:
  server:
    image: sanghoonjeong/allchive-dev:latest
    container_name: server
    hostname: server
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    expose:
      - 8080

  nginx:
    depends_on:
      - server
    restart: always
    build:
      dockerfile: Dockerfile
      context: './nginx'
    ports:
      - "80:80"