server:
  servlet:
    context-path: /api
  forward-headers-strategy: framework

spring:
  profiles:
    include:
      - domain
      - core
      - infrastructure
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    tags-sorter: alpha

swagger:
  user: ${SWAGGER_USER:user}
  password: ${SWAGGER_PASSWORD:password}

---
spring:
  config:
    activate:
      on-profile: dev