spring:
  profiles:
    include:
      - domain
      - core
      - infrastructure
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    tags-sorter: alpha

---
spring:
  config:
    activate:
      on-profile: dev